# NumPy


<a id='index-1'></a>

## Overview

Recall that [NumPy](https://numpy.org/) is a library used for numerical programming and, for data science purposes, we are particularly interested in its extensiove support for array. It is widely used in academia, finance and industry, and is also mature, fast, stable and under continuous development.  


In this notebook we will review the parts of numpy that are most relevant to this module: its support for arrays, which goes way beyond what is included in base python.

### References

- [The notebook shared in class](https://datamining-2023s1-g8s0.github.io/live/topics/03-Data_Handling/01-Python-Numpy/files/introToNumpy.ipynb)
- [The official NumPy documentation](https://numpy.org/doc/stable/reference/).  


## NumPy reminder

The essential problem that NumPy solves is fast array processing.

The most important structure that NumPy defines is an array data type formally called a [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html).

NumPy arrays power a large proportion of the scientific Python ecosystem.

Let’s first import the library.

In [107]:
import numpy as np

## Exercises


<a id='np-ex1'></a>

Mark Hogan 20098168

### Exercise 1

Create a 3x3 (3 rows, 3 columns) array containing the 9 integers 1 .. 9.

1. Extract the following parts of the matrix a:

- the second row
- the third colum
- the top left element

2. How do we get the type and dimensions of a?

3. Compute the following:

- the average (arithmetic mean) of the first row
- the sum of the second column
- the (elementwise) _multiplicative inverse_ of the elements in a (recall that, if $a_{ij}$ is an element of a, its multiplicative inverse is $\frac{1}{a_{ij}}$).

4. How do we find the elements of a that are greater than or equal to 5?

3x3 matrix and then it displays the second row

In [108]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], np.int32)
y = a[1,:]
y



array([4, 5, 6])

getting third column

In [109]:
y = a[:,2]
y

array([3, 6, 9])

the value in the top lef of the matrix (first value)

In [110]:
y = a[0,0]
y

1

gets data type of the matrix

In [111]:
type(a)

numpy.ndarray

gets the mean value of the first row

In [112]:
y = a[0,:]
y.mean()

2.0

adds all numbers in the second column

In [113]:
y = a[:,1]
y.sum()

15

multiplication iverse of each value in the array

In [114]:
y = a/1
y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

all values greater than or equal to 5

In [115]:
y = a[a >= 5]
y

array([5, 6, 7, 8, 9])

### Exercise 2

1. Generate the following arrays

- a matrix a of zeros with 2 rows and 3 columns
- a matrix b of ones with the same dimensions, but the elements are integers
- a random matrix c, whose elements are randomly distributed in [0,1], with the same dimensions
- the transpose of c, d
- the matrix product, e, of c and d
- 11 linearly spaced floating numbers between 1 and 2

2. Explain what happens in the following: `c1 = zeros(3); c2 = c1; c2[0] = 1`.

3. In the matrix c above, find the row having the largest value in the 3rd column.

this creates 3 matrix arrays with 2 rows and 3 columns, first all zeros, second is 1 to 6 and the third is random numbers between 0 and 1 then d = the transpose of c which switches the rows and columns.

In [116]:
a = np.array([[0,0,0], [0,0,0]])
b = np.array([[1,2,3], [4,5,6]], np.int32)
c = np.random.rand(2, 3)
d = c.T
d

array([[0.06513164, 0.25339642],
       [0.5225702 , 0.29969338],
       [0.58590599, 0.22129308]])

this is a matrix multiplication multiplying each value of both arrays which is then = e

In [117]:
e = c@d
e

array([[0.62060758, 0.3027719 ],
       [0.3027719 , 0.2029965 ]])

creates array of 11 evenly spaced numbers between 0 and 2

In [118]:
np.linspace( 0, 2, 11 )

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

first this fails because it needs to be np.zeros, the it creates a array of 3 zeros. Then it points a new variable to the array and changes the first value to 1 of the pointer to the array in turn changing the first value in c1 also

In [119]:
c1 = np.zeros(3); 
c2 = c1; 
c2[0] = 1

row with max number on the 3rd column

In [120]:
f = c[:, 2].max()
c[c[:, 2] == f]

array([[0.06513164, 0.5225702 , 0.58590599]])